export interface CodingTip {
  emoji: string;
  en: string;
  es: string;
}

export const CODING_TIPS: CodingTip[] = [
  { emoji: "🧠", en: "Name things for the reader, not the writer.", es: "Nombra las cosas pensando en quien lee, no en quien escribe." },
  { emoji: "🪄", en: "Make the simple case effortless. Optimize the common path.", es: "Haz que el caso simple sea trivial. Optimiza el camino común." },
  { emoji: "🚦", en: "Fail loudly in dev, gracefully in prod.", es: "Falla con ruido en dev, con elegancia en producción." },
  { emoji: "🧪", en: "If it's hard to test, it's probably wrongly designed.", es: "Si es difícil de testear, probablemente está mal diseñado." },
  { emoji: "🪞", en: "Mirror your domain in code — vague names hide bugs.", es: "Refleja tu dominio en el código — los nombres vagos esconden bugs." },
  { emoji: "🧹", en: "Boy Scout rule: leave the code cleaner than you found it.", es: "Regla del scout: deja el código más limpio de como lo encontraste." },
  { emoji: "⚙️", en: "Premature abstraction is worse than premature optimization.", es: "Una abstracción prematura es peor que una optimización prematura." },
  { emoji: "📦", en: "Cohesion over coupling — keep what changes together, together.", es: "Cohesión sobre acoplamiento — lo que cambia junto, va junto." },
  { emoji: "📜", en: "Comments explain why. Code explains what.", es: "Los comentarios explican el porqué. El código explica el qué." },
  { emoji: "🛠", en: "Small, frequent commits beat one heroic commit.", es: "Commits pequeños y frecuentes ganan al commit heroico." },
  { emoji: "🐛", en: "Reproduce the bug before fixing it.", es: "Reproduce el bug antes de arreglarlo." },
  { emoji: "🪜", en: "Refactor in tiny safe steps — don't free-fall.", es: "Refactoriza en pasos seguros y pequeños — no te lances al vacío." },
  { emoji: "📐", en: "Make illegal states unrepresentable.", es: "Haz que los estados ilegales no se puedan representar." },
  { emoji: "🧭", en: "Optimize for reading. Code is read 10× more than it's written.", es: "Optimiza para leer. El código se lee 10× más de lo que se escribe." },
  { emoji: "🎯", en: "Each function should do one thing well.", es: "Cada función debe hacer una sola cosa, y hacerla bien." },
  { emoji: "🧱", en: "Pure functions are the cheapest tests money can buy.", es: "Las funciones puras son los tests más baratos del mercado." },
  { emoji: "🧯", en: "Errors are values — handle them like data, not surprises.", es: "Los errores son valores — manéjalos como datos, no como sorpresas." },
  { emoji: "📊", en: "Measure before you tune. Guesses are expensive.", es: "Mide antes de optimizar. Adivinar sale caro." },
  { emoji: "🔁", en: "If you write it twice, refactor it once.", es: "Si lo escribes dos veces, refactoriza una." },
  { emoji: "💾", en: "Cache invalidation is hard. Cache less.", es: "Invalidar la caché es difícil. Cachea menos." },
  { emoji: "🪟", en: "Side effects belong at the edges of your system.", es: "Los efectos secundarios viven en los bordes del sistema." },
  { emoji: "🧵", en: "Concurrency bugs hide in shared mutable state.", es: "Los bugs de concurrencia se esconden en el estado mutable compartido." },
  { emoji: "🎨", en: "Design tokens > magic numbers.", es: "Design tokens > números mágicos." },
  { emoji: "🚀", en: "Ship small. Ship often. Iterate.", es: "Entrega pequeño. Entrega seguido. Itera." },
  { emoji: "🔍", en: "Read the error message — twice.", es: "Lee el mensaje de error — dos veces." },
  { emoji: "🧬", en: "Types are documentation that can't lie.", es: "Los tipos son documentación que no puede mentir." },
  { emoji: "🪺", en: "Avoid deep nesting. Flatten with early returns.", es: "Evita el anidado profundo. Aplánalo con early returns." },
  { emoji: "📚", en: "Read code for fun. It's how seniors level up.", es: "Lee código por placer. Así suben de nivel los seniors." },
  { emoji: "🛡", en: "Validate at the boundary. Trust the inside.", es: "Valida en el borde. Confía dentro." },
  { emoji: "🧮", en: "If you're using flags, you probably need polymorphism.", es: "Si usas flags, probablemente necesitas polimorfismo." },
  { emoji: "🌱", en: "Defaults matter — most users never change them.", es: "Los valores por defecto importan — la mayoría nunca los cambia." },
  { emoji: "🛰", en: "Logs are stories. Tell the next dev what happened.", es: "Los logs son historias. Cuéntale al próximo dev qué pasó." },
  { emoji: "🪢", en: "Decoupled code is code you can delete fearlessly.", es: "El código desacoplado se puede borrar sin miedo." },
  { emoji: "🔐", en: "Never log secrets. Never. Not even \"just once\".", es: "Nunca loguees secretos. Nunca. Ni \"solo una vez\"." },
  { emoji: "🎛", en: "Feature flags are great. Stale flags are not.", es: "Los feature flags son geniales. Los flags olvidados no." },
  { emoji: "🧰", en: "Use the boring tool. Boring is reliable.", es: "Usa la herramienta aburrida. Lo aburrido es confiable." },
  { emoji: "🛏", en: "Sleep before merging. Future-you will thank you.", es: "Duerme antes de mergear. Tu yo futuro lo agradecerá." },
  { emoji: "🎢", en: "Production is the only environment that matters.", es: "Producción es el único entorno que importa." },
  { emoji: "🪙", en: "TODOs without owners die. Add a name and a date.", es: "Los TODOs sin dueño mueren. Agrega un nombre y una fecha." },
  { emoji: "📎", en: "When in doubt, write the test first.", es: "Si dudas, escribe el test primero." },
  { emoji: "🎩", en: "Don't be clever. Be obvious.", es: "No seas listo. Sé obvio." },
  { emoji: "🪐", en: "The shortest path to learning is shipping.", es: "El camino más corto para aprender es lanzar." },
  { emoji: "🛠", en: "Fix the bug class, not just the bug.", es: "Arregla la clase de bug, no solo el bug." },
  { emoji: "🪟", en: "If you can't draw it, you don't understand it yet.", es: "Si no puedes dibujarlo, todavía no lo entiendes." },
  { emoji: "🧿", en: "Watch out for time, locales, and floats. They lie.", es: "Cuidado con el tiempo, locales y floats. Mienten." },
  { emoji: "📡", en: "Network is unreliable. Treat it like that.", es: "La red es poco confiable. Trátala como tal." },
  { emoji: "🚪", en: "Build small entrances and small exits — easy to onboard, easy to remove.", es: "Construye entradas y salidas pequeñas — fácil de adoptar, fácil de quitar." },
  { emoji: "⚡", en: "Render less. Hydrate less. Ship less JavaScript.", es: "Renderiza menos. Hidrata menos. Envía menos JavaScript." },
  { emoji: "🎬", en: "Animate intent, not decoration.", es: "Anima la intención, no la decoración." },
  { emoji: "🔭", en: "Observe production with the same care you write code.", es: "Observa producción con el mismo cuidado con que escribes código." },
  { emoji: "🪜", en: "Step debugging beats print debugging — once you set it up.", es: "Depurar paso a paso le gana al print debugging — una vez configurado." },
  { emoji: "🛟", en: "Idempotency saves you from retries gone wild.", es: "La idempotencia te salva de retries descontrolados." },
  { emoji: "🌐", en: "Localize from day one — it's painful to retrofit.", es: "Localiza desde el día uno — meterlo después duele." },
  { emoji: "🦾", en: "Accessibility is a feature, not a checkbox.", es: "La accesibilidad es una feature, no un checkbox." },
  { emoji: "📏", en: "Lint your code. Fights about style waste careers.", es: "Lintea tu código. Las peleas de estilo desperdician carreras." },
  { emoji: "🌗", en: "Test the dark theme. It always breaks.", es: "Prueba el tema oscuro. Siempre se rompe." },
  { emoji: "🛸", en: "AI tools are pair programmers, not pilots.", es: "Las herramientas de IA son pair programmers, no pilotos." },
  { emoji: "🪦", en: "Delete dead code aggressively — it haunts the codebase.", es: "Borra código muerto sin piedad — embruja el codebase." },
  { emoji: "🧊", en: "Memoize when measured. Not when imagined.", es: "Memoriza cuando lo midas. No cuando lo imagines." },
  { emoji: "🧭", en: "Architecture is the cost of changing your mind.", es: "La arquitectura es el costo de cambiar de opinión." },
  { emoji: "💡", en: "The best code is the code you didn't have to write.", es: "El mejor código es el que no tuviste que escribir." },
];
